name: Maven Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: GPG Setup
        run: |
          mkdir ~/.gnupg
          echo "pinentry-mode loopback" | tee -a ~/.gnupg/gpg.conf

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 17

      - name: GPG Sign JAR
        run: |
          gpg --import ~/.ssh/id_rsa.pub
          mvn gpg:sign-artifacts

      - name: Set artifactId
        id: set-artifactId
        run: echo "::set-output name=artifactId::select2-java-selenium"

      - name: Publish to Maven Central
        uses: actions/upload-artifact@v3
        with:
          path: target/select2-java-selenium-1.0.jar
          name: ${{ steps.set-artifactId.outputs.artifactId }}-${{ env.version }}.jar
          repository: maven
          url: https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/
          credentials: ${{ secrets.OSSRH_PAT }}

      - name: Publish to GitHub Packages
        uses: actions/upload-artifact@v3
        with:
          path: target/select2-java-selenium-1.0.jar
          name: ${{ steps.set-artifactId.outputs.artifactId }}-${{ env.version }}.jar
          repository: github
          owner: eotsevych
          repo: select2-java-selenium
