name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Start selenoid
        uses: Xotabu4/selenoid-github-action@v2
      - uses: actions/checkout@v1

      - name: Build with Maven
        run: mvn -B package --file pom.xml test